CREATE SCHEMA IF NOT EXISTS features;

CREATE TABLE IF NOT EXISTS features.base (
    observation_id UBIGINT PRIMARY KEY,
    uuid VARCHAR,
    user_id UBIGINT,
    init_taxon_id UBIGINT,
    init_rank_level INTEGER,
    observed_on DATE,
    created_at TIMESTAMPTZ,
    obs_to_submit_lag_days INTEGER,
    submitted_year INTEGER,
    observed_week_sin DOUBLE,
    observed_week_cos DOUBLE,
    observed_month_sin DOUBLE,
    observed_month_cos DOUBLE,
    submitted_week_sin DOUBLE,
    submitted_week_cos DOUBLE,
    submitted_month_sin DOUBLE,
    submitted_month_cos DOUBLE,
    photo_count INTEGER,
    has_description BOOLEAN,
    has_tags BOOLEAN,
    tag_count INTEGER,
    license_code VARCHAR,
    has_license BOOLEAN,
    positional_accuracy_m DOUBLE,
    obscured BOOLEAN,
    geoprivacy VARCHAR,
    taxon_geoprivacy VARCHAR,
    captive BOOLEAN,
    oauth_application_id UBIGINT,
    has_orcid BOOLEAN,
    owners_id_from_vision BOOLEAN,
    latitude DOUBLE,
    longitude DOUBLE,
    place_guess VARCHAR,
    taxon_id UBIGINT,
    scraped_at VARCHAR
);

CREATE TABLE IF NOT EXISTS features.observations (
    observation_id UBIGINT PRIMARY KEY,
    user_id UBIGINT,
    taxon_id UBIGINT,
    created_at TIMESTAMPTZ,
    observer_tenure INTERVAL,
    is_veteran BOOLEAN,
    has_orcid BOOLEAN,
    observer_obs_count_at_t UBIGINT,
    observer_rg_count_at_t UBIGINT,
    expected_rg_rate DOUBLE,
    observer_rg_rate_at_t DOUBLE,
    observer_reputation_raw DOUBLE,
    observer_reputation_diff DOUBLE,
    rg_rate_is_reliable BOOLEAN,
    observer_taxon_obs_count_at_t UBIGINT,
    observer_taxon_obs_rg_count_at_t UBIGINT,
    observer_taxon_rg_rate_raw_at_t DOUBLE,
    observer_taxon_rg_rate_shrunk_at_t DOUBLE,
    observer_taxon_focus_rate DOUBLE,
    lag_since_last_obs INTERVAL,
    taxon_diversity_order UBIGINT,
    taxon_diversity_family UBIGINT,
    taxon_diversity_genus UBIGINT,
    avg_photo_count DOUBLE,
    pct_obs_with_description DOUBLE,
    pct_obs_with_license DOUBLE,
    pct_obs_from_mobile DOUBLE,
    observer_reputation_rank DOUBLE
);

CREATE TABLE IF NOT EXISTS features.identifications (
    observation_id UBIGINT PRIMARY KEY,
    prior_ids_received UBIGINT,
    prior_identifier_diversity UBIGINT,
    prior_taxa_received_on UBIGINT,
    prior_ids_received_disagree_rate DOUBLE,
    prior_ids_received_agree_rate DOUBLE,
    prior_observer_rg_rate DOUBLE,
    prior_ids_given UBIGINT,
    prior_observers_helped UBIGINT,
    prior_taxa_identified UBIGINT,
    prior_ids_vision_rate DOUBLE,
    reciprocity_ratio DOUBLE
);

CREATE TABLE IF NOT EXISTS features.model_population (
    observation_id UBIGINT PRIMARY KEY,
    uuid VARCHAR,
    user_id UBIGINT,
    init_taxon_id UBIGINT,
    init_rank_level INTEGER,
    observed_on DATE,
    created_at TIMESTAMPTZ,
    obs_to_submit_lag_days INTEGER,
    submitted_year INTEGER,
    observed_week_sin DOUBLE,
    observed_week_cos DOUBLE,
    observed_month_sin DOUBLE,
    observed_month_cos DOUBLE,
    submitted_week_sin DOUBLE,
    submitted_week_cos DOUBLE,
    submitted_month_sin DOUBLE,
    submitted_month_cos DOUBLE,
    photo_count INTEGER,
    has_description BOOLEAN,
    has_tags BOOLEAN,
    tag_count INTEGER,
    license_code VARCHAR,
    has_license BOOLEAN,
    positional_accuracy_m DOUBLE,
    obscured BOOLEAN,
    geoprivacy VARCHAR,
    taxon_geoprivacy VARCHAR,
    captive BOOLEAN,
    oauth_application_id UBIGINT,
    has_orcid BOOLEAN,
    owners_id_from_vision BOOLEAN,
    latitude DOUBLE,
    longitude DOUBLE,
    place_guess VARCHAR,
    taxon_id UBIGINT,
    scraped_at VARCHAR
);

CREATE TABLE IF NOT EXISTS features.label (
    observation_id UBIGINT PRIMARY KEY,
    label BOOLEAN
);

CREATE TABLE IF NOT EXISTS features.splits (
    observation_id UBIGINT PRIMARY KEY,
    split VARCHAR
);
